In [1]:
from scipy.optimize import minimize, rosen, rosen_der

x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize(rosen, x0, method='Nelder-Mead')
res.x

array([ 0.99910115,  0.99820923,  0.99646346,  0.99297555,  0.98600385])

In [2]:
res = minimize(rosen, x0, method='BFGS', jac=rosen_der, options={'gtol': 1e-6, 'disp': True})

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 52
         Function evaluations: 64
         Gradient evaluations: 64


In [3]:
res.x

array([ 1.,  1.,  1.,  1.,  1.])

In [4]:
fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2

cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - 2 * x[1] + 2},
        {'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
        {'type': 'ineq', 'fun': lambda x: -x[0] + 2 * x[1] + 2})

bnds = ((0, None), (0, None))

res = minimize(fun, (2, 0), method='SLSQP', bounds=bnds, constraints=cons)
res.x

array([ 1.4,  1.7])

### Try this, from

http://cars9.uchicago.edu/software/python/lmfit/model.html#model.best_fit

In [5]:
import numpy as np

def gaussian(x, amp, cen, wid):
    return amp * np.exp(-(x-cen)**2. /wid)

from scipy.optimize import curve_fit
x = np.linspace(-10,10)
y = gaussian(x, 2.33, 0.21, 1.51) + np.random.normal(0, 0.2, len(x))

init_vals = [1, 0, 1]     # for [amp, cen, wid]
best_vals, covar = curve_fit(gaussian, x, y, p0=init_vals)
print best_vals

[ 2.30114703  0.1579566   1.5148398 ]
